### ISSUE TITLE
NoClassDefFoundError

### ISSUE THREAD

**Issue by krzysztofantczak** [johna1203/getGists#7]
Plugin doesn't seems to work with Webstorm WS-131.48

NoClassDefFoundError: org/jetbrains/plugins/github/GithubSettings: org/jetbrains/plugins/github/GithubSettings

**Comment by ABabiy** [comment]
Unfortunately, the problem remained

**Comment by leaderliang** [comment]
hi johna1203:
I have encountered some problems on android studio；

`
java.lang.IllegalStateException: Single account auth is deprecated
	at org.jetbrains.plugins.github.util.GithubSettings.getAuthData(GithubSettings.java:129)
	at com.kodokux.github.GithubGetGistAction$2.run(GithubGetGistAction.java:116)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:736)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:395)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
`
