### ISSUE TITLE
It doesn't seems to work on Intellij 15.0.2

### ISSUE THREAD

**Issue by nicolasxu** [johna1203/getGists#22]

**Comment by sloanlance** [comment]
FWIW, it worked for me using IntelliJ IDEA 2016 Ultimate. At least, for viewing and retrieving simple gists. There were problems with more complex operations, though.

**Comment by qikkeronline** [comment]
I also have this issue. Most of the open issues right now seem related (for a lot of people the plugin is broken)

**Comment by charmby** [comment]
NoSuchMethodError: com.intellij.codeInsight.lookup.impl.LookupImpl.addItem(Lcom/intellij/codeInsight/lookup/LookupElement;Lcom/intellij/codeInsight/completion/PrefixMatcher;)V

**Comment by qikkeronline** [comment]
@johna1203 any chance this can be looked into? :-)

**Comment by silvafabio** [comment]
Try this on: https://plugins.jetbrains.com/plugin/11080-use-gists
